# Generated by Django 4.2.5 on 2023-10-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_customuser_facebookd_customuser_isfacebookuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='FaceBookD',
            new_name='FaceBookID',
        ),
    ]
