# Generated by Django 4.2.5 on 2023-10-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteGoogleUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_movie_id', models.IntegerField()),
                ('google_id', models.BigIntegerField()),
            ],
            options={
                'unique_together': {('tmdb_movie_id', 'google_id')},
            },
        ),
    ]
